import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Ledger } from '../lib/ledger.js';
import { Worker } from '../lib/worker.js';
const file=id=>({id,name:id+'.png',mimeType:'image/png',createdTime:new Date().toISOString()});
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'medicine-test-'));const ledger=new Ledger(path.join(dir,'test.sqlite'));let files=[file('old')],ready=true;const sends=[];const drive={configured:true,list:async()=>files,download:async f=>Buffer.from(f.id)};const worker=new Worker({ledger,drive,target:'5511999999999',analyze:async()=> 'Resposta',send:async(target,answer)=>{sends.push({target,answer});return {id:'message-1'};},isReady:()=>ready});t.after(()=>{ledger.close();fs.rmSync(dir,{recursive:true,force:true});});return {ledger,worker,sends,drive,setFiles:v=>files=v,setReady:v=>ready=v};}
test('baseline ignores historical images; new files send only once across polls',async t=>{const f=fixture(t);await f.worker.tick();assert.equal(f.sends.length,0);f.setFiles([file('old'),file('new')]);await f.worker.tick();await f.worker.tick();assert.equal(f.sends.length,1);assert.equal(f.ledger.counts().sent,1);});
test('disconnected WhatsApp queues new images without calling AI or sending',async t=>{const f=fixture(t);await f.worker.tick();f.setReady(false);f.worker.analyze=()=>{throw new Error('must not analyze');};f.setFiles([file('new')]);await f.worker.tick();assert.equal(f.ledger.counts().queued,1);assert.equal(f.sends.length,0);});
test('identical bytes under different file IDs are not sent twice',async t=>{const f=fixture(t);await f.worker.tick();f.drive.download=async()=>Buffer.from('same');f.setFiles([file('a'),file('b')]);await f.worker.tick();assert.equal(f.sends.length,1);assert.equal(f.ledger.counts().duplicate,1);});
test('ambiguous send failure is never automatically retried',async t=>{const f=fixture(t);await f.worker.tick();let attempts=0;f.worker.send=async()=>{attempts++;throw new Error('connection lost');};f.setFiles([file('new')]);await f.worker.tick();await f.worker.tick();assert.equal(attempts,1);assert.equal(f.ledger.counts().uncertain,1);});
test('restart preserves sent records and quarantines interrupted sends',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'medicine-restart-'));const p=path.join(dir,'db.sqlite');let l=new Ledger(p);l.discover([]);l.discover([file('sent'),file('interrupted'),file('analyzing')]);l.update('sent',{status:'sent'});l.update('interrupted',{status:'sending'});l.update('analyzing',{status:'analyzing'});l.close();l=new Ledger(p);assert.deepEqual(l.counts(),{queued:1,sent:1,uncertain:1});l.close();fs.rmSync(dir,{recursive:true,force:true});});
test('failed Drive scan does not mark baseline initialized',async t=>{const f=fixture(t);f.drive.list=async()=>{throw new Error('unavailable');};await f.worker.tick();assert.equal(f.ledger.get('initialized'),undefined);assert.ok(f.worker.error);});
test('analysis failures back off instead of sending an error as an answer',async t=>{const f=fixture(t);await f.worker.tick();f.worker.analyze=async()=>{throw new Error('quota');};f.setFiles([file('new')]);await f.worker.tick();assert.equal(f.sends.length,0);assert.equal(f.ledger.counts().queued,1);assert.equal(f.ledger.next(),undefined);});
